exports.TYPE_NONE = 'NONE';
exports.TYPE_PASS = 'PASS';
exports.TYPE_RUSH = 'RUSH';
exports.TYPE_PENALTY = 'PENALTY';
exports.TYPE_PUNT = 'PUNT';
exports.TYPE_FIELDGOAL = 'FIELDGOAL';
exports.TYPE_KICKOFF = 'KICKOFF';
exports.TYPE_EXTRA_POINT = 'EXTRA_POINT';
exports.TYPE_SACK = 'SACK';

exports.SCORE_NONE = 'NONE';
exports.SCORE_OFF_TOUCHDOWN = 'OFF_TOUCHDOWN';
exports.SCORE_DEF_TOUCHDOWN = 'DEF_TOUCHDOWN';
exports.SCORE_ST_TOUCHDOWN = 'ST_TOUCHDOWN';
exports.SCORE_FIELDGOAL = 'FIELDGOAL';
exports.SCORE_EXTRA_POINT = 'EXTRA_POINT';
exports.SCORE_TWOPT_CONVERSION = 'TWOPT_CONVERSION';
exports.SCORE_SAFETY = 'SAFETY';

exports.TURNOVER_NONE = 'NONE';
exports.TURNOVER_UNDEFINED = 'UNDEFINED';
exports.TURNOVER_FUMBLE = 'FUMBLE';
exports.TURNOVER_INTERCEPTION = 'INTERCEPTION';
exports.TURNOVER_ON_DOWNS = 'ON_DOWNS';
