'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
var TYPE_NONE = exports.TYPE_NONE = 'NONE';
var TYPE_PASS = exports.TYPE_PASS = 'PASS';
var TYPE_RUSH = exports.TYPE_RUSH = 'RUSH';
var TYPE_PENALTY = exports.TYPE_PENALTY = 'PENALTY';
var TYPE_PUNT = exports.TYPE_PUNT = 'PUNT';
var TYPE_FIELDGOAL = exports.TYPE_FIELDGOAL = 'FIELDGOAL';
var TYPE_KICKOFF = exports.TYPE_KICKOFF = 'KICKOFF';
var TYPE_EXTRA_POINT = exports.TYPE_EXTRA_POINT = 'EXTRA_POINT';
var TYPE_SACK = exports.TYPE_SACK = 'SACK';

var SCORE_NONE = exports.SCORE_NONE = 'NONE';
var SCORE_OFF_TOUCHDOWN = exports.SCORE_OFF_TOUCHDOWN = 'OFF_TOUCHDOWN';
var SCORE_DEF_TOUCHDOWN = exports.SCORE_DEF_TOUCHDOWN = 'DEF_TOUCHDOWN';
var SCORE_ST_TOUCHDOWN = exports.SCORE_ST_TOUCHDOWN = 'ST_TOUCHDOWN';
var SCORE_FIELDGOAL = exports.SCORE_FIELDGOAL = 'FIELDGOAL';
var SCORE_EXTRA_POINT = exports.SCORE_EXTRA_POINT = 'EXTRA_POINT';
var SCORE_TWOPT_CONVERSION = exports.SCORE_TWOPT_CONVERSION = 'TWOPT_CONVERSION';
var SCORE_SAFETY = exports.SCORE_SAFETY = 'SAFETY';

var TURNOVER_NONE = exports.TURNOVER_NONE = 'NONE';
var TURNOVER_UNDEFINED = exports.TURNOVER_UNDEFINED = 'UNDEFINED';
var TURNOVER_FUMBLE = exports.TURNOVER_FUMBLE = 'FUMBLE';
var TURNOVER_INTERCEPTION = exports.TURNOVER_INTERCEPTION = 'INTERCEPTION';
var TURNOVER_ON_DOWNS = exports.TURNOVER_ON_DOWNS = 'ON_DOWNS';